GET https://api.nbrb.by/exrates/rates?periodicity=0 HTTP/1.1

###############################################################################

GET http://127.0.0.1:8080/v1/todays_rates HTTP/1.1

###############################################################################

GET http://127.0.0.1:8080/v1/rates_by_date?date=2024-06-28 HTTP/1.1

###############################################################################

GET http://127.0.0.1:8080/v1/rates_dump HTTP/1.1

###############################################################################

GET http://127.0.0.1:8080/health HTTP/1.1
